# Generated by Django 5.2.8 on 2025-11-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraintbug', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schema_editor: apps.get_model('constraintbug', 'Bob').objects.create()),
        migrations.RunPython(lambda apps, schema_editor: apps.get_model('constraintbug', 'Jane').objects.create(
            bob=apps.get_model('constraintbug', 'Bob').objects.first()
        )),
    ]
