# Generated by Django 5.2.8 on 2025-11-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraintbug', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(  # this should fail!!!
            name='Bob',
        ),
    ]
