# Generated by Django 5.2.8 on 2025-11-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraintbug', '0004_add_bob'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schema_editor: apps.get_model('constraintbug', 'Jane').objects.create(
            bob_id=1234,  # there is no such bob with pk 1234, this should fail!!!
        )),
    ]
